port 6380
bind 127.0.0.1
databases 2
maxmemory 512mb
# Delete least recently used keys when reaching maxmemory-policy
maxmemory-policy allkeys-lru
# 1 key within 900s (~15min)
save 900 1
# 10 keys within 300s (~5min)
save 300 10
# 30 key within 60s (1 key every 2s)
save 60 30
# Don't track each individual changes (stick to automatic snapshots)
appendonly no