from .text_resources import (
    QUICKGUIDE_CONTENT,
    INTERPRETATION_HELP_CONTENT,
    COMPUTE_TOOLTIP_CONTENT,
    ANOMALY_TOOLTIP_CONTENT,
    CLIMATOLOGY_TOOLTIP_CONTENT,
    DISCLAIMER_CONTENT
)